### ISSUE TITLE
Script exits before download without any alerts

### ISSUE THREAD

**Issue by AlexRizzuto** [ToTheMax/Snapchat-All-Memories-Downloader#10]
Had an issue with the script hanging and exiting on the initial CDN-LINKS portion. It was happening inconsistently, but typically for me around the end of the JSON (around 4000 items). Dug into it a little bit and it looks like it happens when a lot of 500 errors are being returned from Snapchat (not sure why, didn't dig into why these 500 errors were being returned just checked the status codes). I was able to circumvent by effectively removing the 200 status code validation on line 90 in main.js so the script would progress to downloading without exiting. I think the issue is with error handling in this area of the script.

<img width="966" alt="Screen Shot 2020-08-19 at 3 05 42 PM" src="https://user-images.githubusercontent.com/20031850/90679151-c41f1b00-e22d-11ea-83f0-4796e276cb60.png">

**Comment by ToTheMax** [comment]
Thanks for mentioning!
Yes I've also seen some 500 errors before when I did a lot of downloads in a certain time-span
Probably snapchats servers limiting the amount of downloads.

It is hard to replicate and find the issue, seems like you fixed it!
Could you make a pull request so I can have a look / merge it into this project?

**Comment by trevorbayless** [comment]
Looks like I might be running into this same issue:

![image](https://user-images.githubusercontent.com/3620552/101052598-70baa980-354c-11eb-8e2d-d846baa15aae.png)

I'll look into this on my side as well and make a pull request if I get things working properly.

**Comment by ToTheMax** [comment]
Sure, thanks!

**Comment by ToTheMax** [comment]
Did multiple tests but still can't replicate this error, will close the issue for now

**Comment by ToTheMax** [comment]
The script had some improper error handling. It should now show an error message instead of silently exit. 
I can't replicate the error so would be really interested in this message, please let me know when you see it!
