### ISSUE TITLE
Windows Script Host error

### ISSUE THREAD

**Issue by Gwen1804** [ToTheMax/Snapchat-All-Memories-Downloader#12]
Hey,

I tried to use your program after searching for help like 2 weeks. But when I use it, I have this error. I really hope that you will help me... I have a huge number of snap to download ahah !

Thanks and sorry if my english isn't so good.

![image](https://user-images.githubusercontent.com/71555243/93667806-e7392680-fa88-11ea-960d-7afc66f41333.png)

**Comment by ToTheMax** [comment]
Are you running the script with node? (So not by double licking the file!)

Please check this other issue: https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/issues/4
