### ISSUE TITLE
File Creation Time

### ISSUE THREAD

**Issue by MitchTalmadge** [ToTheMax/Snapchat-All-Memories-Downloader#13]
Hey, thanks for the tool!

Just by looking at the code, it doesn't look like the file creation time is updated to match the recorded timestamp. Would you be open to me adding this functionality by PR? 

A major benefit is that when uploading the memories to a service like Google Photos, it will automatically put the memories in chronological order with other photos and videos already stored.

I suggest we use https://github.com/baileyherbert/utimes to accomplish the task of updating the timestamp.

Let me know what you think! Thanks!

**Comment by ToTheMax** [comment]
Hi Mitch!

Yes that would be a good upgrade!
However, most of the users of this script are not really familiar with node(/npm) so I tried to create the script without external packages. 
I'm not sure if this is also possible without a package, maybe you can check that out.
If it's not, we can update the readme so the user needs to run "npm install" before executing the script.

Will definitely be down to merge your PR!

**Comment by MitchTalmadge** [comment]
Thanks! I see what you mean and I'll try to do this without npm. I have a few ideas. :)

**Comment by ToTheMax** [comment]
Cool, goodluck! If I can do something let me know

**Comment by MitchTalmadge** [comment]
Appreciated! It may take a bit, I am having a busier than expected week. I'll let you know once I have a PR ready!

**Comment by MitchTalmadge** [comment]
Just wanted to update you, things are going well and creation times are being written to the files. A downside is that I could not find a way to do this without npm. The `utimes` package I linked is the only one of its kind, and it requires some native binaries to be built, which `npm` must be used for. If you don't want to do this, I totally understand, and I'd be happy to just keep my own fork for my own purposes. 

I have been debugging a little bit and that's taking me some extra time because my snapchat downloads keep expiring as I get sidetracked with schoolwork. I'll have something for you soon if you're cool with using npm -- all that happens is we ask the user to run `npm install` first.

**Comment by ToTheMax** [comment]
Yeah sure, then we just add `npm install` in the guide!

**Comment by vstene** [comment]
@MitchTalmadge Do you think you can create a pull request on the feature?

**Comment by MitchTalmadge** [comment]
@vstene yep! Thanks for reminding me. I got so busy. Here is the PR: #22. Last I checked it worked pretty well, but I would appreciate you testing it and feel free to add anything I missed. I guess you would need to fork my fork or something.. I don't know how collaboration works here lol.
