### ISSUE TITLE
Newbie - I cannot get this to work!

### ISSUE THREAD

**Issue by exterminate010** [ToTheMax/Snapchat-All-Memories-Downloader#15]
Hi Max. As in title, I am brand new to this and was wondering if you could help me?

I followed all the steps, and I opened PowerShell directly in the folder and then typed in 

> node main.js 

and pressed Enter. 

The script then executed but then said this as it ran through the files

CDN-LINKS: [====================] 3555/3768 Failed: 0
DOWNLOADS: [====================] 0/3768 Failed: 0

**It then stops and no files have downloaded**. I am a complete newbie to this, so a quick guide would be great. Thanks again for creating this script!

**Comment by ToTheMax** [comment]
Hmm then something is going wrong. It doesn't give any errors?

**Comment by exterminate010** [comment]
Hi Max, it doesn't give any errors whatsoever!

Ian Redington
________________________________

**Comment by ToTheMax** [comment]
I just tested the script on my own memories, the script should still work.
Can you try limiting the amount of concurrent downloads, for example:
```node -c 10 main.js```
If that doesn't work, can you try to request a new zip-file from snapchat? Download-links expire over time.

**Comment by exterminate010** [comment]
Hi Max,

I have requested a new zip-file and will try and limit the amount of concurrent downloads as above!

**Comment by exterminate010** [comment]
Hi Max, followed your instructions and this error message came up in Powershell:

'internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'C:\Users\Exter\Documents\Snapchat Memories\mydata~1602592412429\10'
←[90m    at Module._resolveFilename (internal/modules/cjs/loader.js:831:15)←[39m
←[90m    at internal/main/check_syntax.js:32:20←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []'

Any tips on how to fix?

**Comment by exterminate010** [comment]
I have just followed all the steps with a brand new Zip file of snapchat and freshly downloaded code and still coming up with this:

PS C:\Users\Exter\Documents\mydata~1602592412429> `node main.js`
CDN-LINKS: [===================-] 3750/3924     Failed: 0
DOWNLOADS: [--------------------] 0/3924        Failed: 0

PS C:\Users\Exter\Documents\mydata~1602592412429>

Sorry for the constant queries, I really appreciate the responses. Hopefully can get this fixed and stop bothering you!

**Comment by exterminate010** [comment]
Hi Max, any chance of an update on why this does not work?

**Comment by ToTheMax** [comment]
Could you add me on discord? ToTheMax#2203
