### ISSUE TITLE
Help it says it cant find node main.js

### ISSUE THREAD

**Issue by Siebrenyolo** [ToTheMax/Snapchat-All-Memories-Downloader#16]
When i double click the main.js it gives me this error
![image](https://user-images.githubusercontent.com/54123577/95479055-9da67200-098a-11eb-923e-5a85e18925ea.png)

How can i fix it?

**Comment by ToTheMax** [comment]
Please check the other issues: https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/issues/4

**Comment by Siebrenyolo** [comment]
Thank you! Really nice script btw , now i'm rly getting into scripts!

**Comment by ToTheMax** [comment]
Cool! Glad to help
