### ISSUE TITLE
The process stops, and cannot be done

### ISSUE THREAD

**Issue by martijjx** [ToTheMax/Snapchat-All-Memories-Downloader#17]
Process stops at different progress.
![Screenshot from 2020-10-11 21-22-45](https://user-images.githubusercontent.com/72708396/95688102-f0d92880-0c07-11eb-9a45-c07a458436f3.png)

**Comment by ToTheMax** [comment]
Oh wow, that terminal output looks weird, what Linux distro are you using?
I wrote custom code for that progress bar that works on my machine, might want to use an npm package for that.

**Comment by martijjx** [comment]
It's ubuntu 20.04. I'm just new to this stuff, Could you please instruct me how to do it step by step?

**Comment by martijjx** [comment]
here is another example
![Screenshot from 2020-10-11 21-52-13](https://user-images.githubusercontent.com/72708396/95688683-2da71e80-0c0c-11eb-9129-17dd9be84fde.png)

**Comment by ToTheMax** [comment]
You are doing it right, does it just stop at a certain point?
What happens when you set `-c 1`

**Comment by martijjx** [comment]
Its not certain point, I started from c equal to 50, and when I restart linux it often go little further

**Comment by martijjx** [comment]
When I set c to 1 it also ended up at some point

**Comment by ToTheMax** [comment]
Could you try to get a fresh .zip file from Snapchat? Links seem to expire over time, maybe that is the problem.

**Comment by martijjx** [comment]
Yes, I tried but I'll try it once more

**Comment by martijjx** [comment]
My Linux is also fully booted from pendrive if it matters

**Comment by martijjx** [comment]
I got fresh zip from snap and it's still not working

**Comment by martijjx** [comment]
And also it looks the same on win10

**Comment by martijjx** [comment]
I've done it once more and its downloading :)

**Comment by exterminate010** [comment]
Damn, I've done the same with no luck!
________________________________
