### ISSUE TITLE
File checking before downloading

### ISSUE THREAD

**Issue by bloworlf** [ToTheMax/Snapchat-All-Memories-Downloader#18]
Hello,
Thank you for this tool, it is very helpful. I would never have patience to click on over 3000 link to get my files. Thank you again.

I noticed a few things that could help a little. Since Snapchat only allows people to get a file a limited number in a day, you could check if a file already exists. If so, check if the downloaded file's size matches the size of the file to download. If not, download and replace the existing file. This can prevent people from downloading one single file several times in case of network disconnected for example. (I downloaded over 1000 files twice)

I'm not familiar with node... so that suggestion is the only thing I can do.

Great work.

**Comment by bloworlf** [comment]
![IMG_20201012_150514](https://user-images.githubusercontent.com/39887108/95781691-5c6cd580-0c9c-11eb-85df-9b8356a11815.jpg)

**Comment by ToTheMax** [comment]
Good to hear it was helpful! Definitely a good suggestion, will take a look at it in the coming weeks

**Comment by ToTheMax** [comment]
With the latest update failed links will be retried multiple times, hope this solves the issue!
