### ISSUE TITLE
Noob

### ISSUE THREAD

**Issue by flowergirlrose** [ToTheMax/Snapchat-All-Memories-Downloader#19]
Hi! I have no idea what im doing really. I downloaded my zip file and opened it and I downloaded the node.js terminal I keep trying to type things in but none of it is right. im on a Mac by the way. please help! all I know how to code is html and css

**Comment by ToTheMax** [comment]
Hello! this problem seems to be more personal, could you add me on discord? ToTheMax#2203
I might be able to help you if you can send screenshots where you are stuck ;)

**Comment by charlieleach** [comment]
Hi im also having issues with using it on Mac, I added you on discord as well

**Comment by charlieleach** [comment]
no worries got it working, thanks so much!

**Comment by ToTheMax** [comment]
Cool, no problem!
