### ISSUE TITLE
Issue with progress

### ISSUE THREAD

**Issue by letivalo** [ToTheMax/Snapchat-All-Memories-Downloader#20]
I closed out the command prompt before remembering to screenshot it XD.
It was something like ... "download: 679iled failed: 0"
Everything downloaded fine, just a little glitch in how things were written out in cmd.

**Comment by ToTheMax** [comment]
Was it like that the entire run? It can happen when you rescale the window or something

**Comment by kaolinn** [comment]
Yeah the entire run, this was my window sizing.
![Screenshot 2020-11-12 140207](https://user-images.githubusercontent.com/74377668/98996315-e0aab680-24ef-11eb-8034-0067f1916627.png)

**Comment by kaolinn** [comment]
![image](https://user-images.githubusercontent.com/74377668/98996560-4b5bf200-24f0-11eb-9389-09c716eeb4ba.png)

**Comment by kaolinn** [comment]
![Uploading image.png…]()

**Comment by kaolinn** [comment]
![image](https://user-images.githubusercontent.com/74377668/98996666-79413680-24f0-11eb-9456-1fa74febe6b1.png)

**Comment by kaolinn** [comment]
![Screenshot 2020-11-12 140821](https://user-images.githubusercontent.com/74377668/98996714-8cec9d00-24f0-11eb-837f-88ae92b46732.png)

**Comment by ToTheMax** [comment]
Ah okay I see, must be a bug in my code, wrote this progress bar myself (since I didnt want to use external packages)
Will have a look at it, thanks for mentioning!

**Comment by KittyJutsu** [comment]
Any news ?

**Comment by ToTheMax** [comment]
I tried to replicate it on my own machine but couldn't do it. 
Do you have the same problem? @KittyJutsu This logging error is just a visual bug, does the script itself work?
