### ISSUE TITLE
Syntax Error 800A03EA

### ISSUE THREAD

**Issue by Anmyks** [ToTheMax/Snapchat-All-Memories-Downloader#21]
Hey Max,

I found this as a reply to a stackoverflow post you replied to a while ago and thought it would be a BLESSING to have this kind of code.

I downloaded it and followed the instructions, but whenever I click on main.js, it gives me this:

![hhukhjkhj](https://user-images.githubusercontent.com/35441294/99417033-700efa00-2934-11eb-809f-f24fcf99f4a1.PNG)

Any advice?

**Comment by ToTheMax** [comment]
You should run the file through cmd, not by double clicking it. See: https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/issues/4#issuecomment-664035581

**Comment by Anmyks** [comment]
Works, thanks!

**Comment by ToTheMax** [comment]
Cool!
