### ISSUE TITLE
Caption Strips and Post Effects missing

### ISSUE THREAD

**Issue by devinbaeten** [ToTheMax/Snapchat-All-Memories-Downloader#23]
When exported theres's no text or post capture effects rendered on the image. is this meta data that can be compiled later or is it unavailable?

**Comment by ToTheMax** [comment]
Oh I didn't even notice, your totally right! 
Snapchat unfortunately doesn't provide post capture effects on the download links. This data probably gets stored on their servers and don't think we can retrieve it.
