### ISSUE TITLE
MODULE_NOT_FOUND :(

### ISSUE THREAD

**Issue by bambi-ai** [ToTheMax/Snapchat-All-Memories-Downloader#25]
I'm pretty new to this so I'm having trouble figuring out what I'm doing wrong! I keep getting this MODULE_NOT_FOUND error, even though the folder has what it's saying is missing. Any ideas? Thanks in advance!
![image](https://user-images.githubusercontent.com/13178396/101856804-0bf6e480-3b34-11eb-9343-6f3ba8c6a3d8.png)

**Comment by ToTheMax** [comment]
You need to first run `npm install` then it should work!
