### ISSUE TITLE
 Cannot find module '../../binding.node'

### ISSUE THREAD

**Issue by msogamer** [ToTheMax/Snapchat-All-Memories-Downloader#26]
So ya i just tryed launching and i got like 4 errors fixed a lot but this cant go away
![image](https://user-images.githubusercontent.com/59775830/102605937-ba031f80-412e-11eb-80b9-ed82865b624e.png)

**Comment by ToTheMax** [comment]
Did you install the modules by running `npm install` first?

**Comment by msogamer** [comment]
> Did you install the modules by running `npm install` first?

![image](https://user-images.githubusercontent.com/59775830/102608929-56c7bc00-4133-11eb-98c3-7e5313fc2752.png)
yes I did

**Comment by ToTheMax** [comment]
Thats really weird, is a node_modules folder created after calling npm install?

**Comment by jme-wan** [comment]
I am having the same issue. Previously it said cannot find module 'moment' and I just tried running npm install which created the node_modules folder; ran the script again to extract memories_history.json and now the error states cannot find module 'utimes'

**Comment by ToTheMax** [comment]
Can you also try `npm install utimes` and then start it

**Comment by db-ctrl** [comment]
I'm getting this same issue. Using node version 15.5.0. Followed all the steps in the readme file. 

@ToTheMax  , I just tried `npm install utimes` . No luck unfortunately though. Do you think i should try an earlier node version?

![image](https://user-images.githubusercontent.com/56555962/103156905-7e5afc00-47a5-11eb-9780-65b6c6644a9f.png)

**Comment by ToTheMax** [comment]
Ah okay that's weird. You can try out older version of the script which doesn't require any modules: https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/tree/7108846391fb92df919d79789514faedb4461098
I'll look for a fix when I can find time

**Comment by db-ctrl** [comment]
> Ah okay that's weird. You can try out older version of the script which doesn't require any modules: https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/tree/7108846391fb92df919d79789514faedb4461098
> I'll look for a fix when I can find time

Awesome mate. Just wanted to say, this is a cool little tool you've made here. I've been trying to get my data off all social medias. It would take me years to manually press the download button on all my memories hahah

**Comment by jme-wan** [comment]
Thank you! The link below worked for me.

Jaimie

**Comment by jme-wan** [comment]
Hm, it seems to have paused suddenly as I have memories that go beyond 2018...is there any way to reboot it without it downloading copies? Thank you!



    On Monday, December 28, 2020, 11:51:49 PM PST, Jaimie Wan <j.me_wan@yahoo.com> wrote:  
 
 Thank you! The link below worked for me.

Jaimie

On Dec 27, 2020, at 9:12 PM, db-ctrl <notifications@github.com> wrote:



﻿



Ah okay that's weird. You can try out older version of the script which doesn't require any modules: https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/tree/7108846391fb92df919d79789514faedb4461098
I'll look for a fix when I can find time


Awesome mate. Just wanted to say, this is a cool little tool you've made here. I've been trying to get my data off all social medias. It would take me years to manually press the download button on all my memories hahah

**Comment by ToTheMax** [comment]
Hmm I think its going wrong on the server's side, can you try to request a new zipfile and try it again?

**Comment by jme-wan** [comment]
For some reason when I tried to run it on a new zip file, nothing ended up downloading so I just tried one more time with the original and everything downloaded!

Thank you so much for this!

Is there anyway to send you a small token of gratitude? Do you have a buymeacoffee link?

Thank you again!

Jaimie

**Comment by ToTheMax** [comment]
Ah good to hear it worked!
Yes you can donate me here paypal.me/mraams
Thanks so much! Really appreciate it!

**Comment by 5cj** [comment]
> I'm getting this same issue. Using node version 15.5.0. Followed all the steps in the readme file.
> 
> @ToTheMax , I just tried `npm install utimes` . No luck unfortunately though. Do you think i should try an earlier node version?
> 
> ![image](https://user-images.githubusercontent.com/56555962/103156905-7e5afc00-47a5-11eb-9780-65b6c6644a9f.png)

I know this is a very old issue, but I was able to fix the "Error: Cannot find module '../build/Release/binding.node'" by deleting the `node_modules` directory and running `npm install` again

**Comment by ToTheMax** [comment]
Thanks for mentioning!
