### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by scotty286262** [ToTheMax/Snapchat-All-Memories-Downloader#28]
hi there,
i still cant figure our what im doing wrong
any help would be appriciated[
![Screen Shot 2020-12-26 at 20 45 11](https://user-images.githubusercontent.com/76630448/103158949-76a65200-47bb-11eb-92a9-c92a532e1618.png)
](url)

**Comment by ToTheMax** [comment]
Something seems to go wrong, please look at my latest reply in another thread https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/issues/26#issuecomment-751382700

**Comment by scotty286262** [comment]
dont worry, i managed to get it working. just had to put the whole json file into it, not just the memories on its own. thank you so much
