### ISSUE TITLE
SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by VincentXE** [ToTheMax/Snapchat-All-Memories-Downloader#30]
Hey, great script but when I try to use it, it gives me this error. 
![image](https://user-images.githubusercontent.com/17298607/103447911-56f9a880-4c57-11eb-9f52-c091e4788748.png)

`C:\Users\vince\Documents\MyData>node main.js -c 30 -f .\memories_history.html
C:\Users\vince\Documents\MyData\memories_history.html:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<'
[90m    at wrapSafe (internal/modules/cjs/loader.js:979:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1027:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m
    at Object.<anonymous> (C:\Users\vince\Documents\MyData\main.js:20:17)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
`

Thanks

**Comment by ToTheMax** [comment]
Hi Vincent, you must provide the `.json` file: `memories_history.json`
