### ISSUE TITLE
SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by macrohumanity** [ToTheMax/Snapchat-All-Memories-Downloader#33]
![Snapchat Memory Issue](https://user-images.githubusercontent.com/71165719/107730678-422a1f00-6cb1-11eb-9f93-a8a4d1fbbc7c.png)

Image Attached.

Hey ToTheMax, 
First of all, great job on writing a useful script like this!

GNU/Linux (Ubuntu 18.04) user here.
I know nothing about JavaScript so I am unable to fix my own issue...

As you can see from the image, I have...
-  pre-installed <nodejs>
- moved my <memories_history.json> to <Snapchat-All-Memories-Downloader>
- <npm install>

NOTE : <node main.js> does not work for me (depicted in image).

The problem is... after entering <node>,
<main.js -c 50 -f ./json/memories_history.json> results in a <SyntaxError: Unexpected number>

Thank you in advance for the help!

**Comment by ToTheMax** [comment]
Please pass these arguments in one line (don't press enter after typing `node`). The full command is:
```node main.js -c 50 -f ./json/memories_history.json```
The script also can't find your json file, so please provide the correct filepath

**Comment by macrohumanity** [comment]
![Snapchat Memory Issue (1)](https://user-images.githubusercontent.com/71165719/107786455-2ce1de80-6d0b-11eb-8b70-90817cc64a11.png)

First command given in this image attachment will show the path of where I have <memories_history.json>.
Full path : </home/wobbalinux/Deskop/Snapchat-All-Memories-Downloader-master/memories_history.json>

It seems that both command...
<node main.js -c 50 -f ./json/memories_history.json>
<node main.js -c 30 -f ./json/memories_history.json>
 will give the 'throw' error depicted in the image attachment.
This is why I initially separated <node> from the rest of the code.

**Comment by macrohumanity** [comment]
![Snapchat Memory Issue (2)](https://user-images.githubusercontent.com/71165719/107789570-fc03a880-6d0e-11eb-8052-cffe6007b8b8.png)

Here some other approaches using the full path in the code.

The first command given in the image attachment is the closest that I have came to being successful.
Two other variation attempts are depicted in the image attachment.

**Comment by ToTheMax** [comment]
The first one seems to be the correct path, can you request a new zip file from Snapchat and try it like that again? The links might be expired

**Comment by macrohumanity** [comment]
Complete. 
No luck. 
I wish that I knew JS... 
Do you have any other suggestions?

**Comment by ToTheMax** [comment]
The problem really seems to be in the filepath you are providing, are you 100% sure the file is there?
I'm closing this issue for now as I am doing a clean-up, feel free to open a new one
