### ISSUE TITLE
SyntaxError: Unexpected token '/'

### ISSUE THREAD

**Issue by kralcbelac** [ToTheMax/Snapchat-All-Memories-Downloader#35]
I am stuck here :
<img width="339" alt="Screen Shot 2021-04-22 at 4 17 22 PM" src="https://user-images.githubusercontent.com/83038129/115779664-41cf9380-a386-11eb-8092-3f8886f7142c.png">
<img width="565" alt="Screen Shot 2021-04-22 at 4 18 02 PM" src="https://user-images.githubusercontent.com/83038129/115779736-56ac2700-a386-11eb-9ad0-11628ad7f891.png">

**Comment by ToTheMax** [comment]
Make sure your terminal is in the correct folder, apparently the current folder doesn't have a `main.js`
( Use `cd` to go through folders and `ls` to list files )
