### ISSUE TITLE
Slow download ?

### ISSUE THREAD

**Issue by colorful77** [ToTheMax/Snapchat-All-Memories-Downloader#37]
Hey,

When using your downloader for the first today I noticed download speed was extremely slow , no matter the number of concurrent connections I used

Any fix ?

Thanks

**Comment by ToTheMax** [comment]
Hi! 
Probably the snapchat servers (or your own internet connection) having a very low bandwidth.
You can try to request a new zip file from Snapchat, fresh download links might be faster.
Goodluck!
