### ISSUE TITLE
Syntax Compilation Error Line 2?

### ISSUE THREAD

**Issue by dthomas710** [ToTheMax/Snapchat-All-Memories-Downloader#4]
Hello, 

This sounds like a wonderful little script that I'd love to download and get working. I will admit I'm quite a huge novice but I believe I've followed all instructions properly, but I'm running into a persistent issue that I need help with. I will copy the error message here. The scripts are properly placed in the extracted zip file downloaded from snap, and it will not work when trying to run main.js. Placing the scripts in the html doesn't help even though that's not part of the instructions. I'm not technically savvy enough to try to attempt to modify the -f flag myself but based on your instructions that shouldn't matter if I've copied the scripts into the extracted zip from snap. Currently runing node.js version 12.18.3. 

Here is the error message:

![snap download error](https://user-images.githubusercontent.com/68824903/88487676-170df700-cf3c-11ea-98e0-5b6a46f84cc2.png)

Thank you so much for your help. Please let me know if there is any other information I can provide!

Since this is going to save me so much time and hassle I'd love to donate to help support once I can get it working!

**Comment by ToTheMax** [comment]
Hi Thomas!

Nice to hear you are using my script!
A syntax error usually says there must be something wrong with the code,
that shouldn't be the case.
The javascript shouldn't be placed in the html! It needs to run with Node.

How did you run the script? Double clicking on it will probably not work.
You need to open cmd.exe or powershell and run the script from there.
If you need help with that please let me know so I can give you some
instructions!

Kind regards,
Max

Op zo 26 jul. 2020 om 21:35 schreef dthomas710 <notifications@github.com>:

**Comment by dthomas710** [comment]
Hello, 

Yes, I was attempting to double click it, I guess that's what I was doing wrong. Please assist with addtl instructions, I'm a huge novice. 

Thank you!

**Comment by alexrobinson1999** [comment]
Hi there!
Also a novice here wondering how to execute the program. 
On a windows PC, with the files within the snapchat data folder and unsure how to procees as 'right click' 'open with command prompt' doens't run the program and I'm unsure what to do next.
Would be very grateful for a step-by-step explanation!
Many thanks for your work

**Comment by ToTheMax** [comment]
Ah okay no problem guys!
I think the easiest way is to open cmd/powershell directly in the folder, there are two options:
- Shift + rightclick in the folder and then click on something like "Open powershell here"
- In the address bar of the folder type: cmd

A new window will open with a command line, there you can type ```node main.js``` and press enter.
The script should then execute, please let me know if it works!

**Comment by dthomas710** [comment]
BOOM!

Thanks Max. That did it right away. You're awesome! 

Thank you so much for your help and quick responses! I'd love to buy you a beer to support, anywhere where I can drop a few bucks?

**Comment by ToTheMax** [comment]
No problem, very good to hear! 
You can donate me over here: https://www.paypal.me/mraams
Thanks in advance, means a lot!

**Comment by alexrobinson1999** [comment]
Ah I just hadn't placed the files in the correct location! First tried in the html then the json and finally outside of both and that's perfect.

Incredible timing that someone else was going through the same at the same time!

Thanks a bunch mate! And thanks for the code, it makes life a hell of a lot easier.
Alex

**Comment by dthomas710** [comment]
Fantastic, glad you were able to help us both. I just dropped a small donation!

Have a great finish to your weekend and stay safe out there. 

Issue closed.

**Comment by romydveen** [comment]
Hi, I wanted to download my memories, right now I downloaded my snapchat data, Ive got json, html, and index.html
But what do I have to do now, I am not good and codering or anything, I hope you can help me.

**Comment by ToTheMax** [comment]
If you really can't find a way, you can add me on discord so I can walk you through: ToTheMax#2203

**Comment by romydveen** [comment]
Thankyou so much!!! I've added you on discord!

**Comment by arshu333** [comment]
Bro, when i try it  via shell, it gives me an error.  

PS C:\Users\Arshu\Desktop\SNap> node main.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'moment'
Require stack:
- C:\Users\Arshu\Desktop\SNap\main.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m
    at Object.<anonymous> (C:\Users\Arshu\Desktop\SNap\main.js:6:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'C:\\Users\\Arshu\\Desktop\\SNap\\main.js'[39m ]
}

please help me out

**Comment by ToTheMax** [comment]
Did you first run: `npm install` ?

**Comment by Siebrenyolo** [comment]
i have the same problem. I tried to run npm install but it didnt do much.
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@7.6.0
2 info using node@v15.11.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 7ms
5 timing config:load:builtin Completed in 7ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:D:\Downloads\mydata_1615131686668\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\siebr\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\siebr\AppData\Roaming\npm\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 14ms
19 verbose npm-session 3b18de8b89278727
20 timing npm:load Completed in 26ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 36ms
23 timing idealTree:userRequests Completed in 0ms
24 silly idealTree buildDeps
25 timing idealTree:#root Completed in 0ms
26 timing idealTree:buildDeps Completed in 1ms
27 timing idealTree:fixDepFlags Completed in 0ms
28 timing idealTree Completed in 39ms
29 timing reify:loadTrees Completed in 41ms
30 timing reify:diffTrees Completed in 1ms
31 silly reify moves {}
32 timing reify:retireShallow Completed in 1ms
33 timing reify:createSparse Completed in 3ms
34 timing reify:loadBundles Completed in 0ms
35 timing reifyNode:node_modules/utimes Completed in 246ms
36 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 504ms
37 timing auditReport:getReport Completed in 507ms
38 timing auditReport:init Completed in 0ms
39 timing reify:audit Completed in 507ms
40 timing reifyNode:node_modules/node-addon-api Completed in 521ms
41 timing reifyNode:node_modules/moment Completed in 1087ms
42 timing reify:unpack Completed in 1088ms
43 timing reify:unretire Completed in 1ms
44 timing build:queue Completed in 2ms
45 info run utimes@4.0.2 install node_modules/utimes node-gyp rebuild
46 info run utimes@4.0.2 install { code: 1, signal: null }
47 timing reify:rollback:createSparse Completed in 275ms
48 timing reify:rollback:retireShallow Completed in 0ms
49 timing command:install Completed in 11088ms
50 verbose stack Error: command failed
50 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
50 verbose stack     at ChildProcess.emit (node:events:378:20)
50 verbose stack     at maybeClose (node:internal/child_process:1067:16)
50 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
51 verbose pkgid utimes@4.0.2
52 verbose cwd D:\Downloads\mydata_1615131686668
53 verbose Windows_NT 10.0.19041
54 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
55 verbose node v15.11.0
56 verbose npm  v7.6.0
57 error code 1
58 error path D:\Downloads\mydata_1615131686668\node_modules\utimes
59 error command failed
60 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
61 error gyp info it worked if it ends with ok
61 error gyp info using node-gyp@7.1.2
61 error gyp info using node@15.11.0 | win32 | x64
61 error gyp info find Python using Python version 3.9.2 found at "C:\Users\siebr\AppData\Local\Programs\Python\Python39\python.exe"
61 error gyp http GET https://nodejs.org/download/release/v15.11.0/node-v15.11.0-headers.tar.gz
61 error gyp http 200 https://nodejs.org/download/release/v15.11.0/node-v15.11.0-headers.tar.gz
61 error gyp http GET https://nodejs.org/download/release/v15.11.0/SHASUMS256.txt
61 error gyp http GET https://nodejs.org/download/release/v15.11.0/win-x86/node.lib
61 error gyp http GET https://nodejs.org/download/release/v15.11.0/win-arm64/node.lib
61 error gyp http GET https://nodejs.org/download/release/v15.11.0/win-x64/node.lib
61 error gyp http 200 https://nodejs.org/download/release/v15.11.0/SHASUMS256.txt
61 error gyp http 200 https://nodejs.org/download/release/v15.11.0/win-x64/node.lib
61 error gyp http 404 https://nodejs.org/download/release/v15.11.0/win-arm64/node.lib
61 error gyp http 200 https://nodejs.org/download/release/v15.11.0/win-x86/node.lib
61 error gyp ERR! find VS
61 error gyp ERR! find VS msvs_version not set from command line or npm config
61 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
61 error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
61 error gyp ERR! find VS looking for Visual Studio 2015
61 error gyp ERR! find VS - not found
61 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
61 error gyp ERR! find VS
61 error gyp ERR! find VS **************************************************************
61 error gyp ERR! find VS You need to install the latest version of Visual Studio
61 error gyp ERR! find VS including the "Desktop development with C++" workload.
61 error gyp ERR! find VS For more information consult the documentation at:
61 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
61 error gyp ERR! find VS **************************************************************
61 error gyp ERR! find VS
61 error gyp ERR! configure error
61 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
61 error gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
61 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
61 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
61 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
61 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
61 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
61 error gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
61 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
61 error gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
61 error gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
61 error gyp ERR! System Windows_NT 10.0.19041
61 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
61 error gyp ERR! cwd D:\Downloads\mydata_1615131686668\node_modules\utimes
61 error gyp ERR! node -v v15.11.0
61 error gyp ERR! node-gyp -v v7.1.2
61 error gyp ERR! not ok
62 verbose exit 1

**Comment by ToTheMax** [comment]
I see errors about a missing VS installation, please take a look at this stackoverflow answer: https://stackoverflow.com/a/63311413/7334699

**Comment by Cipkek** [comment]
Hi, I've been trying to run it for some time, but it stops after downloading approximetly 2,5GB and all the filetypes are "FILE". Am I doing something wrong ?

**Comment by TheTechRobo** [comment]
Please open a new issue for this

**Comment by maikeila22** [comment]
> Bro, when i try it via shell, it gives me an error.
> 
> PS C:\Users\Arshu\Desktop\SNap> node main.js internal/modules/cjs/loader.js:883 throw err; ^
> 
> Error: Cannot find module 'moment' Require stack:
> 
> * C:\Users\Arshu\Desktop\SNap\main.js
>   �[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)�[39m
>   �[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)�[39m
>   �[90m    at Module.require (internal/modules/cjs/loader.js:952:19)�[39m
>   �[90m    at require (internal/modules/cjs/helpers.js:88:18)�[39m
>   at Object. (C:\Users\Arshu\Desktop\SNap\main.js:6:16)
>   �[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)�[39m
>   �[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)�[39m
>   �[90m    at Module.load (internal/modules/cjs/loader.js:928:32)�[39m
>   �[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)�[39m
>   �[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)�[39m {
>   code: �[32m'MODULE_NOT_FOUND'�[39m,
>   requireStack: [ �[32m'C:\Users\Arshu\Desktop\SNap\main.js'�[39m ]
>   }
> 
> please help me out

i have the same problem did you solve the problem?

**Comment by ToTheMax** [comment]
Did you first run `npm install` in your commandline?

**Comment by maikeila22** [comment]
Yes
