### ISSUE TITLE
why aborting without error?

### ISSUE THREAD

**Issue by Keki1337** [ToTheMax/Snapchat-All-Memories-Downloader#44]
```
e@ubuntu:~/Downloads/Snapchat-All-Memories-Downloader-master$ node main.js -c 50 -f ./json/memories_history.json
CDN-LINKS: [=-------------------] 846/12121     Failed: 0
DOWNLOADS: [--------------------] 0/12121	Failed: 0
e@ubuntu:~/Downloads/Snapchat-All-Memories-Downloader-master$ 


```

Why is it aborting without error while checking cdn-links?

**Comment by ToTheMax** [comment]
Hmm that's weird, have you tried to run it again? (maybe with a new file)

**Comment by ToTheMax** [comment]
The script had some improper error handling. It should now show an error message instead of silently exit. 
I can't replicate the error so would be really interested in this message, please let me know when you see it!
