### ISSUE TITLE
Aborting without an error...again 2021

### ISSUE THREAD

**Issue by marquavious** [ToTheMax/Snapchat-All-Memories-Downloader#46]
It's just aborting without an error, tried running this 3 times. 
any ideas as to what the issue could be?

![Screen Shot 2021-10-24 at 3 04 09 AM](https://user-images.githubusercontent.com/17103248/138589312-6b3ddab2-97cb-4d9d-beb8-80785fafa192.png)

**Comment by ToTheMax** [comment]
The script had some improper error handling. It should now show an error message instead of silently exit. 
I can't replicate the error so would be really interested in this message, please let me know when you see it!
