### ISSUE TITLE
Not working - All CDN-LINKS failed 

### ISSUE THREAD

**Issue by Mopade** [ToTheMax/Snapchat-All-Memories-Downloader#5]
Hello, 

I dowloaded your script and my snapchat data. 

Unfortunately it doesn't work as you can see below :-( 

Could you help me? 

Thank you

**Comment by Mopade** [comment]
OK, it works in Windows 10, sorry for this topic, you can close this issue :) 
Thank you!

**Comment by ToTheMax** [comment]
Haha no problem! What OS were you using?

**Comment by Mopade** [comment]
I was using Elementary OS, all packages updated and Node.js installed :)

**Comment by ToTheMax** [comment]
Ah weird, I'm using Ubuntu myself and that is working fine.
