### ISSUE TITLE
Failed Links and Downloads

### ISSUE THREAD

**Issue by furyeffect** [ToTheMax/Snapchat-All-Memories-Downloader#52]
So I ran the process correctly on my Macbook and got the downloads and everything to work but then my Macbook ran out of storage so I used my PC to do the proccess and whenever I do it it says all of my memories failed? I did a test run to see if this issue would happen on my Macbook after trying to perform it on my PC and the issue still exists. I also checked to see if the links still work and they download perfectly if I just click on a single one. Any help?

**Comment by ToTheMax** [comment]
Probably has something to do with expired links, could you try to request a new zipfile and try it again?

**Comment by furyeffect** [comment]
I just submitted a new request and got a new file and the issue is still happening. Not sure why it all of a sudden just stopped working because the very first time I did it, it would download all of them just as planned..

**Comment by ToTheMax** [comment]
What happens when you set the -c flag to 1 for example?

**Comment by furyeffect** [comment]
The problem still persists when I switch it to 1

**Comment by furyeffect** [comment]
Update: I have fixed the issue. For some reason if I use my personal hotspot, the script and downloads work but if im connected to my home network, it no longer works? Not sure how this happened but

**Comment by ToTheMax** [comment]
Hmm, weird, might has something to do with IP block. Good you found the solution, will close the issue!
