### ISSUE TITLE
Failed Download

### ISSUE THREAD

**Issue by Ephil012** [ToTheMax/Snapchat-All-Memories-Downloader#54]
I noticed that some of the downloads were randomly failing. When I ran the debugger, I found out that the downloadMemory function was failing due to ECONNRESET. I think the connection to Snapchat's servers randomly resets causing it to fail randomly for some downloads. Is there any workaround for this? I was thinking maybe some sort of retry mechanism should be implemented when it fails.

**Comment by ToTheMax** [comment]
Did you try to download a failing file manually? It might be that those links are just broken that even retrying won't help

**Comment by Ephil012** [comment]
I did try it. The links do work. It just it randomly closes.

**Comment by Ephil012** [comment]
I submitted PR #57 that fixed the issue for me. The links themselves were fine, it's just sometimes the servers the images are being hosted on randomly disconnects and you have the download fail as a result. The PR I made basically just allows it to retry 3 times before it counts it as a failure. This fixed the issue for me and now the downloads work properly.
