### ISSUE TITLE
Unable to download memories of snapchat , please help

### ISSUE THREAD

**Issue by VaruniP** [ToTheMax/Snapchat-All-Memories-Downloader#58]
Hi, Im varuni prakash,

I just downloaded my snapchat backup and tried to follow as per your instructions
[Book1.xlsx](https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/files/7923981/Book1.xlsx)
, but im unable to to download in cmd, please help on below steps. it will be helpful.

i have attached screenshot of the same in excel , pls do share any video or link.

**Comment by ToTheMax** [comment]
Where did you place my scripts? You should but them in that data_XXX folder, and then start cmd from there

**Comment by ToTheMax** [comment]
The scripts you've downloaded from this repository, download them (you might have to unzip), and then place them in that data folder.

**Comment by VaruniP** [comment]
Hi

Currently I have downloaded and extracted the snapchat data only. Not
download any other. Can you please share link to download from.
Thanks

**Comment by VaruniP** [comment]
Hi please share me procedure, to take backup.
Help me out with this.
As per your guidence I have opened cmd and try to provide command with data
path. Still I'm unable to.

Thank

**Comment by ToTheMax** [comment]
Here is the link to download my scripts: https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/archive/refs/heads/master.zip
