### ISSUE TITLE
all failing

### ISSUE THREAD

**Issue by vlw9** [ToTheMax/Snapchat-All-Memories-Downloader#59]
I had trouble installing utimes and I saw your comment about going back to an earlier version so I went to https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/tree/7108846391fb92df919d79789514faedb4461098 and put the snapchat data at the top level but I got this:

CDN-LINKS: [====================] 0/5926        Failed: 5926
DOWNLOADS: [--------------------] 0/5926        Failed: 0

The links are still fresh, I've tried downloading one image from the browser and it works. Any idea what the issue could be?

**Comment by ToTheMax** [comment]
That old version doesn't work anymore, Snapchat changed its file structure, I updated the README
What error do you get when installing utimes?

**Comment by vlw9** [comment]
The utimes issue was related to not having node-gyp and visual studio (and not being able to successfully install it either, including trying with windows-build-tools) but no worries, I used someone else's laptop that was able to do the above and I was able to download my memories. Thanks man!
