### ISSUE TITLE
CDN-LINKS FAILED

### ISSUE THREAD

**Issue by amaterasu95** [ToTheMax/Snapchat-All-Memories-Downloader#62]
Hello, I have just downloaded your script and configured everything by following your instructions, however whenever I try to execute node main.js I encounter an issue which is shown on one of the attached screenshots. 

![snap1](https://user-images.githubusercontent.com/102159829/159488342-c3a1c337-0f26-486d-93c6-74da4b18e01e.PNG)
![snap2](https://user-images.githubusercontent.com/102159829/159488343-b7909ca7-83bf-466f-898d-28e8b08d2c9e.PNG)
![snap3](https://user-images.githubusercontent.com/102159829/159488345-c5a3f889-7978-48f6-8046-d94f35a712e7.PNG)

**Comment by ToTheMax** [comment]
Hi! That's weird, you are doing it the correct way! 
Could you try to request a new zip file from Snapchat? The links might have expired

**Comment by amaterasu95** [comment]
Sounds like good idea, I will give you an update asap.

**Comment by amaterasu95** [comment]
I downloaded fresh zip file from snapchat and everything works fine, thanks for response, help and script, gotta go back to making my album, have a great week!

**Comment by ToTheMax** [comment]
Good to hear! Will close this issue
