### ISSUE TITLE
Saves as invalid file type

### ISSUE THREAD

**Issue by bongobirch** [ToTheMax/Snapchat-All-Memories-Downloader#63]
Whenever I download my memories, it saves as the wrong file type due to the ending of the file being named .04 and such. Is there a way to fix this without manually going through and fixing each one?

![image](https://user-images.githubusercontent.com/84354402/160225063-8af60a46-f185-447f-be39-b2b687a9511a.png)

**Comment by ToTheMax** [comment]
I think you're running an old version of my code, could you redownload the scripts?

**Comment by bongobirch** [comment]
After redownloading it cannot find module: moment. (After updating node.) 

My version for node is: v16.14.2
And for npm: 8.5.0

**Comment by bongobirch** [comment]
Okay I got it working. I had to navigate the command window to the folder and type npm install, then it prompted me to update to the newest version of npm 8.5.5.

Thank you!
