### ISSUE TITLE
Mac Issues

### ISSUE THREAD

**Issue by GitHugz** [ToTheMax/Snapchat-All-Memories-Downloader#68]
Hi, as you've instructed others, I have made an account and added you on discord, and yet discord locked me out unless i give them my phone number, which since they are owned by Microsoft, I am unwilling to do. 

Can you please contact me by email or even reddit messages is preferable to handing over my phone number to Microsoft. 

Thank you for your work, it looks great so far, just have a specific issue.

**Comment by TheTechRobo** [comment]
BTW, Discord isn't owned by Microsoft (as far as I know). 

What's the problem? (I'm not the owner, but I might be able to help)

**Comment by ToTheMax** [comment]
Didn't know Discord requires a phone number, thats annoying. I like your reasoning but like @TheTechRobo says, I don't think Microsoft owns Discord? 
Anyway, are you okay to share your mail or reddit username here so I can contact you?

**Comment by GitHugz** [comment]
Yes, my reddit username is Isotrop3 

Thank you for the speed of reply. 
Please delete my comment once read, and I will remove/close the issue and such.
(Note: Microsoft does not outright own it, but heavy investing in 2021 and talks to acquire, information shared for legality reasons during the "talks". Feel free to read about it, my logic is always: Follow the money.)
