### ISSUE TITLE
Help PLEASE

### ISSUE THREAD

**Issue by ghost** [ToTheMax/Snapchat-All-Memories-Downloader#7]
Hi, thanks for the code btw, its was really difficult finding a thread with people who understood exactly what i was looking for. (kept getting redirected to sites saying, tap in the app, click export, do this one by one....) However i've been struggling to follow the instructions you laid out, wasn't the best programmer in college. (wasn't able to get past the first year of programming) BASICALLY, i was wondering if you could break it down so that someone with little to no programming background could follow along and download their snapchat memories as well. Thanks

**Comment by ToTheMax** [comment]
No problem, would like to help you out ;)
What OS are you using? 
Did you also check out the other closed threads?
