### ISSUE TITLE
Rate limiting on the Snapchat CDN prohibits many concurrent downloads

### ISSUE THREAD

**Issue by villasenor** [ToTheMax/Snapchat-All-Memories-Downloader#70]
Due to rate limiting on the Snapchat CDN, I was seeing many failed downloads when the concurrent downloads were set to the default (`30`). I think that might be a bit high - I set it to `1`, and was successfully able to download everything. Initially, about 100 memories were not able to be downloaded at `30` concurrent downloads. I waited 14 hours and tried again with `1` concurrent download and it worked great.

So maybe change the default and/or adjust the Readme for Docker to show the `-c` option?

Thanks for all your hard work on this project, it's awesome!

**Comment by ToTheMax** [comment]
Thanks for the feedback! On my network I had no problem running 30 (or even 100) concurrent downloads, so it probably depends on your network / the CDN. Setting it just to 1 takes a lot of time when you have a lot of memories. 

I added the `-c` option to the docker readme, hope that makes things clearer!

**Comment by villasenor** [comment]
Hmm yeah, maybe it's because my network speed is high? I'm on a 1000 Mbps connection. Either way, more documentation is always nice. Thanks!
