### ISSUE TITLE
Snapchat has updated their data download feature

### ISSUE THREAD

**Issue by nathen418** [ToTheMax/Snapchat-All-Memories-Downloader#73]
Snapchat has updated its data download feature to now have a toggle to request the memories as downloadable files directly in the zip folder. However, they are stripped of all of their EXIF data, including the date taken, which is not very useful imo.

It also omits the downloading of the `memories_history.json` file, so if a user wants the `memories_history.json` they need to make sure not to select that toggle.

It took me a while to find [a thread on Reddit](https://www.reddit.com/r/DataHoarder/comments/uod00o/comment/j8le6bh/?utm_source=share&utm_medium=web2x&context=3) that confirmed I wasn't crazy. 

It would be helpful to people in the future if you updated the readme to include this information. Took me a while to figure the whole thing out. Otherwise, the scripts still seem to work great.

**Comment by ToTheMax** [comment]
Thanks for mentioning, didn't know of this feature! I updated the README, hope this helps

**Comment by nathen418** [comment]
Awesome, thank you!
