### ISSUE TITLE
New snapchat page idk what to choose

### ISSUE THREAD

**Issue by Dadzzio** [ToTheMax/Snapchat-All-Memories-Downloader#78]
Hey! I want to download all my memories but idk what options i should choose to have memories json file. Before, when I selected all of this and requested data I didn't get memories_history.json. Thanks for help:)
![image](https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/assets/103329834/e2bcb131-3f00-41f6-8727-15b94dcf44b7)

**Comment by ToTheMax** [comment]
Oh that's new! I will add this to the guide.
You should probably enable "Export JSON files"

**Comment by ToTheMax** [comment]
I just checked: they don't seem to add the `memories.json` anymore, will fix my scripts when I have time

**Comment by ToTheMax** [comment]
I just checked, the script still works! The README has been updated so you can see what options to select on the new page

**Comment by PrejudiceNeutrino** [comment]
Yes it still works! Thanks for making this :)

**Comment by Sliffcak** [comment]
I am still confused, what do we do now that memories.json is not available?

**Comment by ToTheMax** [comment]
It is right? If you follow the [README](https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/blob/master/README.md)

**Comment by Sliffcak** [comment]
> It is right? If you follow the [README](https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/blob/master/README.md)

Thanks for the reply. Maybe I am confused. In both methods to run the script you need to provide it a "memories_history.json" file, and specify it as an argument.

However, upon exporting Snapchat data as of today they do not provide the memories_history.json file.  I exported everything available from snapchat data export options page.

**Comment by jensstigaard** [comment]
I am pretty confident that Snapchat mydata now includes memories, when the option "include media files" (or similar) is ticked. This tool is therefore unnecesary/redundant. However the locations are not embedded in the files, AFAIK.

**Comment by Sliffcak** [comment]
> I am pretty confident that Snapchat mydata now includes memories, when the option "include media files" (or similar) is ticked. This tool is therefore unnecesary/redundant. However the locations are not embedded in the files, AFAIK.

You are correct. However, the original timestamps are not preserved, which was something that I believe this tool helped with preserving the original timestamps of the memories. Currently when you tick the setting you are referring to, the Created At and Modified At will be the current time.

**Comment by jensstigaard** [comment]
For video files, I think the details pane in the "properties"-dialog for the file (in Windows Explorer) shows the original creation timestamp. However for images I have not seem the same.

**Comment by Sliffcak** [comment]
To summarize and prevent any future confusion.

If you do not care about the timestamps of the snapchat memories, this tool may not be needed, you can just select the new setting.

![image](https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/assets/19200789/86793238-5a92-4a58-ad95-a82ac3fed66a)

If you care about timestamps of snapchat memories, this tool is great! When you export snapchat data DO NOT select the option shown in the above screenshot, if you select that setting, the memories_history.json file will not be created. Refer to the README for a screenshot of the correct settings to select. 

This ticket can probably be closed.

**Comment by ToTheMax** [comment]
You are both right, this tool is only needed if you want the files with timestamps.
@Sliffcak Thanks for the update, that option indeed needs to be disabled, I will think about updating the README to make this more clear! Have a great day

**Comment by ToTheMax** [comment]
[Update README.md](https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/commit/55e875fae238c1ca07755e891f85804a3deeed8f?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
