### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/Volumes/.....

### ISSUE THREAD

**Issue by binnichtaktiv** [ToTheMax/Snapchat-All-Memories-Downloader#79]
Hi after the program downloaded most of the memories it crashed with the error

jonasb.@iMacvonJonas Snapchat-All-Memories-Downloader % node main.js -f /Volumes/SanDisk/Snapchat-All-Memories-Downloader/mydata~1692638509501/json/memories_history.json -o /Volumes/SanDisk/Snapchat-All-Memories-Downloader/mydata~1692638509501/snap downloads
CDN-LINKS: [====================] 1251/1266	Failed: 15
DOWNLOADS: [==============------] 933/1266      Failed: 0
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, stat '/Volumes/SanDisk/Snapchat-All-Memories-Downloader/mydata~1692638509501/snap/2022-03-09_08-56-22.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Volumes/SanDisk/Snapchat-All-Memories-Downloader/mydata~1692638509501/snap/2022-03-09_08-56-22.jpg'
}

Node.js v20.5.1
jonasb.@iMacvonJonas Snapchat-All-Memories-Downloader % 

the 933 before the program crashed are in the folder and downloaded but the rest is not

**Comment by binnichtaktiv** [comment]
uh i don't know why some things are crossed out i didn't do that on purpose

**Comment by ToTheMax** [comment]
Weird error, did you move files halfway through the process? Maybe try and run again?

**Comment by binnichtaktiv** [comment]
> Weird error, did you move files halfway through the process? Maybe try and run again?

Nah I didnt touch it

I downloaded to my usb stick and now I tried it on my mac directly and it worked without problems :) 
Thanks for that tool🫶🏻

**Comment by ToTheMax** [comment]
Perfect!
