### ISSUE TITLE
Downloads failing for some memories if getFileName returns same name

### ISSUE THREAD

**Issue by akshays92** [ToTheMax/Snapchat-All-Memories-Downloader#84]
I was constantly seeing 150/560 memories fail download. Realized this was because of the files already existing for that name in the downloads folder passed as the arguement.

Solution  I tried was to append a random at the end of each file name and tried again to see all 560 files successfully downloading.

**Comment by gabmackie** [comment]
I'm concerned I have the same problem. Did your solution work? And how exactly did you do it?

**Comment by ToTheMax** [comment]
Thanks for highlighting the issue, I fixed it in https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/commit/dd944cdc9c6e2b3ed832415dc788c7fa06fba625
