### ISSUE TITLE
exiftool is broken due to Docker Node Version & breaking change to exiftool

### ISSUE THREAD

**Issue by autumnesponda** [ToTheMax/Snapchat-All-Memories-Downloader#85]
null coalescing operator was added to exiftool very recently, check it out [here](https://github.com/mattduffy/exiftool/blob/712eabe7d71babd5ee30407cd65a6f5d1b44b88a/src/index.js#L33)
not sure which version of node you want to update python-nodejs to, according to [node.green](https://node.green/#ES2021-features-Logical-Assignment-----basic-support), ?? started being supporting in 15.14. when i pulled this down, i updated my dockerfile to grab latest python-nodejs and it worked fine.

**Comment by ToTheMax** [comment]
Thanks for highlighting the issue! I'll test and update the Docker image soon

**Comment by ToTheMax** [comment]
https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/commit/840cc2773853a6d1f59aaaff062bde918f2f256e
